---
- name: Install Java & Tomcat
  hosts: all
  become: yes

  tasks:
   - name: Installing java in RedHat
     yum:
      name: java
      state: present
     when: ansible_os_family == 'RedHat'
  

   - name: Installing Java in Debian
     apt:
        name: default-jdk
        state: present
     when: ansible_os_family == "Debian"

   - name: download tomcat
     get_url:
       url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.93/bin/apache-tomcat-8.5.93.tar.gz
       dest: /opt

   - name: extract tomcat
     unarchive:
        src:  /opt/apache-tomcat-8.5.93.tar.gz
        dest: /opt
        remote_src: yes

   - name: providing executable permissions
     file:
       path: /opt/apache-tomcat-8.5.93/bin/startup.sh
       mode: 0777
    
   - name: start tomcat service
     ansible.builtin.shell: nohup ./startup.sh
     args:
      chdir: /opt/apache-tomcat-8.5.93/bin        






