--- #Creating files
- name: User from files
  hosts: all
  become: yes

  vars_files:
    - user.yml

  tasks:
    - name: creating user {{user2}}
      user:
        name: "{{user2}}"
        state: present
